eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: product
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xuyisen.com:3306/imc_study?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: imc_study
    password: 1q2w3e
  jpa:
    show-sql: true